### ISSUE TITLE
Add an Issue Tracker and Project Management Module

### ISSUE THREAD

**Issue by DrewBrasher** [OrchardCoreContrib/OrchardCoreContrib.Modules#101]
I would like to help build an open source module that would add Issue Tracker and Project Management features to an Orchard Core CMS site. What is the process for starting a new module in this repository?

**Comment by hishamco** [comment]
Simply you can open the solution and have a look at https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/tree/main/src, like other modules, you can create a new module, then add a reference to [OrchardCoreContrib.Modules.Web](https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/tree/main/src/OrchardCoreContrib.Modules.Web) so you will be able to test your newly added module

**Comment by hishamco** [comment]
I suggest we need to list all the required features as a checklist, then we can track them later easily. I'm waiting for your suggestion then I can participate to why you add

**Comment by DrewBrasher** [comment]
## Definitions
**Issue/Request/Ticket** - Used for reporting problems, requesting new features, or any request for something to be done. I'm not exactly sure what to call this but I will refer to it as an **Issue** for now.

**Project** - A set of related tasks that need to be completed.
## Features
### Common to both an Issue and a Project
- [ ] Title
- [ ] Body (html or markdown)
- [ ] Requestor contact information
- [ ] Assign to one or more users who are responsible for the task
- [ ] Attach files
- [ ] Category
- [ ] Different groups of people should be linked to different categories. For example, IT would be responsible for the category "Computer" and Application Development would be responsible for the "Website" category
- [ ] Status (New, In Progress, completed, cancelled, etc)
- [ ] Priority
- [ ] Comments

### Issue
- [ ] A user should be able to submit an Issue without having access to the admin side
- [ ] Users can view all Issues they have submitted

### Project
- [ ] Multiple Issues can be associated with a project
- [ ] Due Date

### Workflows
- [ ] Users who submitted or are assigned to should be notified when a change is made or comment added
- [ ] Users should be notified when new content is added with a Category they are responsible for

**Comment by hishamco** [comment]
- Projects
- Milestones
- Members
- Issues

**Comment by hishamco** [comment]
@DrewBrasher do you have a plan to start one this?

**Comment by hishamco** [comment]
> Do you have any suggestions for what to name the project?

IssueTracker

**Comment by DrewBrasher** [comment]
I've created a module for this in my https://github.com/DrewBrasher/OrchardCoreContrib.Modules/tree/IssueTrackerModule fork to start working on this. Right now it is just what the visual studio template from Lombiq created.

**Comment by hishamco** [comment]
Normal OC template from within VS

**Comment by DrewBrasher** [comment]
> Normal OC template from within VS

I used the one called "Orchard Core CMS Module".

**Comment by hishamco** [comment]
You could push a draft PR and we might participate with each other

**Comment by hishamco** [comment]
If we can do it seriously, let us write down an MVP, and we can work together on it, because this module is rich, I also need to maintain the other modules

I hope to see this on action
